### ISSUE TITLE
no wlan on alphabot2 with your image

### ISSUE THREAD

**Issue by gstrainovic** [blupants/blupants#1]
Thank you for this great work, but when I bootup from Alphabot2 with pi zero w with Blupants image I don't have wlan to select.

With the newest raspian or Ubuntu desktop it's work. 

How to fix?

Thanks, Goran

**Comment by blupants** [comment]
I have completely missed your message, apologies for that.

Thanks for your kind words.

Have you tried connecting to the WiFi by using a QR code? Please, find the instructions on this video: https://www.youtube.com/watch?v=WPL2GEIYyvs
